### ISSUE TITLE
登录完需要管理审核

### ISSUE THREAD

**Issue by baijianruoliorz** [lvyuanx/CommunitySystem#1]
大佬 想知道这一步逻辑是怎么进行的

**Comment by lvyuanx** [comment]
注册需要审核这部分，我是通过一个字段控制的（比如：type 字段，0未激活，1激活，2注销），默认注册是未激活状态。然后管理员这边可以根据状态字段查询未激活状态用户，将对应得用户状态字段改为1，就完成了管理员激活账户功能。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lvyuanx/CommunitySystem"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月14日(星期一) 上午10:36
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[lvyuanx/CommunitySystem] 登录完需要管理审核 (Issue #1)





 
大佬 想知道这一步逻辑是怎么进行的
