### ISSUE TITLE
401错误

### ISSUE THREAD

**Issue by jasmine795060** [lvyuanx/CommunitySystem#4]
第一次进去就出现401错误怎么办

**Comment by lvyuanx** [comment]
请把页面错误截图我看一下，截图带上network里面的请求

**Comment by jasmine795060** [comment]
感谢，我弄好了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年04月12日 16:54 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [lvyuanx/CommunitySystem] 401错误 (Issue #4) |

请把页面错误截图我看一下，截图带上network里面的请求

**Comment by jasmine795060** [comment]
不过你这个手机端操作像ios，进行处理要滑动，不是点一下，挺好



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年04月12日 16:54 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [lvyuanx/CommunitySystem] 401错误 (Issue #4) |

请把页面错误截图我看一下，截图带上network里面的请求

**Comment by lvyuanx** [comment]
多谢夸奖

**Comment by jasmine795060** [comment]
兄弟，我今天在运行项目时候，手机端网页加载不出来但电脑端能打开网页，咋弄



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年04月24日 18:25 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [lvyuanx/CommunitySystem] 401错误 (Issue #4) |

多谢夸奖
