### ISSUE TITLE
Navicat导入sql文件存在错误

### ISSUE THREAD

**Issue by Emptyio** [lvyuanx/CommunitySystem#5]
在使用navicat导入sql文件时存在32个报错 

![image](https://user-images.githubusercontent.com/92676655/233818956-da37aef6-73bc-4f89-b63b-27150d1d22f7.png)

**Comment by Emptyio** [comment]
Mysql版本：Ver 8.0.32-0ubuntu0.20.04.2

**Comment by lvyuanx** [comment]
你可以考虑使用命令的方式导入sql脚本，我这个脚本也是用navicat导出的，并且也在Ubuntu上运行过了。
